apiVersion: monitoring.pisanix.dev/v1alpha1
kind: CustomHPA
metadata:
  name: sample-web-chpa
  namespace: default
spec:
  minReplicas: 1
  maxReplicas: 5
  intervalSeconds: 30
  targetRef:
    name: sample-web
    namespace: default
