apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: customhpas.monitoring.pisanix.dev
spec:
  group: monitoring.pisanix.dev
  scope: Namespaced
  names:
    plural: customhpas
    singular: customhpa
    kind: CustomHPA
    shortNames:
      - chpa
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [prometheusURL, promQL, minReplicas, maxReplicas, targetRef]
              properties:
                prometheusURL:
                  type: string
                  minLength: 1
                promQL:
                  type: string
                  minLength: 1
                minReplicas:
                  type: integer
                  format: int32
                  minimum: 0
                maxReplicas:
                  type: integer
                  format: int32
                  minimum: 1
                intervalSeconds:
                  type: integer
                  format: int32
                  minimum: 5
                targetRef:
                  type: object
                  required: [name]
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
            status:
              type: object
              properties:
                currentReplicas:
                  type: integer
                  format: int32
                lastQueryValue:
                  type: number
                  format: double
                lastScaleTime:
                  type: string
                  format: date-time
                conditions:
                  type: array
                  items:
                    type: object
                    required: [type, status, lastTransitionTime, reason, message]
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                        enum: ["True","False","Unknown"]
                      lastTransitionTime:
                        type: string
                        format: date-time
                      reason:
                        type: string
                      message:
                        type: string
      additionalPrinterColumns:
        - name: Query
          type: string
          jsonPath: .spec.promQL
        - name: Min
          type: integer
          jsonPath: .spec.minReplicas
        - name: Max
          type: integer
          jsonPath: .spec.maxReplicas
        - name: Target
          type: string
          jsonPath: .spec.targetRef.name
        - name: Replicas
          type: integer
          jsonPath: .status.currentReplicas

